/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QLK.Login;

import QLK.controller.taikhoancontroller;
import QLK.util.PropertiesNVNow;
import QLK.view.KhachHangView;
import QLK.view.KhoView;
import QLK.view.NhaCungCapView;
import QLK.view.NhanVienView;
import QLK.view.QLKHome;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import QLK.view.QuanTriView;
import QLK.view.SanPhamView;
import QLK.view.XuatHome;
import java.util.List;

/**
 *
 * @author Admins
 */
public class Home extends javax.swing.JFrame{

    /**
     * Creates new form Main
     */
    public Home() {
        initComponents();
//        setOpaque(false);
        HideMenu();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    public void PQ(){
        PropertiesNVNow pr = new PropertiesNVNow();
        List<String> l = pr.getRemember();
        lblCV.setText(l.get(1));
        lblTenNV.setText(l.get(2));
        
        String ma =  new PropertiesNVNow().getRemember().get(0);
        int st = new taikhoancontroller().PQ(ma);
        //int st = 1;
        if(st==1){
        //Amin
            btnTK.setVisible(true);
            btnQLTK.setVisible(true);
            btnQLNV.setVisible(true);
            btnDangXuat.setVisible(true);

            btnQL.setVisible(false);
            
            btnNCC.setVisible(false);

            btnKH.setVisible(false);
            
        
        }else if(st==2){
        //quan ly
            btnTK.setVisible(true);
            btnQLTK.setVisible(false);
            btnQLNV.setVisible(false);
            btnDangXuat.setVisible(true);

            btnQL.setVisible(true);
            btnSanPham.setVisible(false);

            btnNCC.setVisible(true);

            btnKH.setVisible(false);

            btnBC.setVisible(true);
            btnQLPT.setVisible(true);
            btnQLSP.setVisible(false);
        
                
        }else if(st==0){
        //nhân viên
            btnTK.setVisible(true);
            btnQLTK.setVisible(false);
            btnQLNV.setVisible(false);
            btnDangXuat.setVisible(true);

            btnQL.setVisible(true);
            btnQLXK.setVisible(true);
            btnK.setVisible(false);

        
        }
    
    }
    

    public void HideMenu()
        {
            //PQ();
            pnSP.setVisible(false);
            pnTK.setVisible(false);
            pnQL.setVisible(false);
            
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnLeft = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblCV = new javax.swing.JLabel();
        lblTenNV = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        pnTK = new javax.swing.JPanel();
        btnDangXuat = new javax.swing.JLabel();
        btnQLTK = new javax.swing.JLabel();
        btnQLNV = new javax.swing.JLabel();
        btnQL = new javax.swing.JLabel();
        btnTK = new javax.swing.JLabel();
        pnQL = new javax.swing.JPanel();
        btnQLXK = new javax.swing.JLabel();
        btnSanPham = new javax.swing.JLabel();
        btnNK = new javax.swing.JLabel();
        btnK = new javax.swing.JLabel();
        btnTT = new javax.swing.JLabel();
        btnExit = new javax.swing.JLabel();
        btnNCC = new javax.swing.JLabel();
        btnKH = new javax.swing.JLabel();
        btnBC = new javax.swing.JLabel();
        pnSP = new javax.swing.JPanel();
        btnQLPT = new javax.swing.JLabel();
        btnQLSP = new javax.swing.JLabel();
        pnHome = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        pnLeft.setBackground(new java.awt.Color(0, 153, 204));

        jPanel4.setBackground(new java.awt.Color(0, 153, 204));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("QuangAnhStore");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Prestige & Quality");

        lblCV.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblCV.setForeground(new java.awt.Color(255, 255, 255));

        lblTenNV.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTenNV.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(lblCV, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTenNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel5))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jLabel6)))
                        .addGap(0, 53, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(14, 14, 14)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTenNV, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(lblCV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setOpaque(false);

        jPanel5.setOpaque(false);

        pnTK.setOpaque(false);

        btnDangXuat.setBackground(new java.awt.Color(255, 255, 255));
        btnDangXuat.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnDangXuat.setForeground(new java.awt.Color(255, 255, 255));
        btnDangXuat.setText("            Đăng xuất");
        btnDangXuat.setMaximumSize(new java.awt.Dimension(150, 28));
        btnDangXuat.setMinimumSize(new java.awt.Dimension(150, 28));
        btnDangXuat.setPreferredSize(new java.awt.Dimension(150, 28));
        btnDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDangXuatMouseClicked(evt);
            }
        });

        btnQLTK.setBackground(new java.awt.Color(255, 255, 255));
        btnQLTK.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnQLTK.setForeground(new java.awt.Color(255, 255, 255));
        btnQLTK.setText("            Quản lý tài khoản");
        btnQLTK.setMaximumSize(new java.awt.Dimension(150, 28));
        btnQLTK.setMinimumSize(new java.awt.Dimension(150, 28));
        btnQLTK.setPreferredSize(new java.awt.Dimension(150, 28));
        btnQLTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLTKMouseClicked(evt);
            }
        });

        btnQLNV.setBackground(new java.awt.Color(255, 255, 255));
        btnQLNV.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnQLNV.setForeground(new java.awt.Color(255, 255, 255));
        btnQLNV.setText("            Quản lý nhân viên");
        btnQLNV.setMaximumSize(new java.awt.Dimension(150, 28));
        btnQLNV.setMinimumSize(new java.awt.Dimension(150, 28));
        btnQLNV.setPreferredSize(new java.awt.Dimension(150, 28));
        btnQLNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLNVMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnTKLayout = new javax.swing.GroupLayout(pnTK);
        pnTK.setLayout(pnTKLayout);
        pnTKLayout.setHorizontalGroup(
            pnTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnQLTK, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
            .addComponent(btnDangXuat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnQLNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnTKLayout.setVerticalGroup(
            pnTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTKLayout.createSequentialGroup()
                .addComponent(btnQLTK, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnQLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(pnTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnQL.setBackground(new java.awt.Color(255, 255, 255));
        btnQL.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnQL.setForeground(new java.awt.Color(255, 255, 255));
        btnQL.setText("Quản Lý");
        btnQL.setIconTextGap(15);
        btnQL.setMaximumSize(new java.awt.Dimension(172, 48));
        btnQL.setMinimumSize(new java.awt.Dimension(172, 48));
        btnQL.setPreferredSize(new java.awt.Dimension(172, 48));
        btnQL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLMouseClicked(evt);
            }
        });

        btnTK.setBackground(new java.awt.Color(255, 255, 255));
        btnTK.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnTK.setForeground(new java.awt.Color(255, 255, 255));
        btnTK.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTK.setText("Quản trị hệ thống");
        btnTK.setIconTextGap(15);
        btnTK.setMaximumSize(new java.awt.Dimension(172, 48));
        btnTK.setMinimumSize(new java.awt.Dimension(172, 48));
        btnTK.setName(""); // NOI18N
        btnTK.setPreferredSize(new java.awt.Dimension(172, 48));
        btnTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTKMouseClicked(evt);
            }
        });

        pnQL.setOpaque(false);

        btnQLXK.setBackground(new java.awt.Color(255, 255, 255));
        btnQLXK.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnQLXK.setForeground(new java.awt.Color(255, 255, 255));
        btnQLXK.setText("            Quản lý xuất kho");
        btnQLXK.setMaximumSize(new java.awt.Dimension(150, 28));
        btnQLXK.setMinimumSize(new java.awt.Dimension(150, 28));
        btnQLXK.setPreferredSize(new java.awt.Dimension(150, 28));
        btnQLXK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLXKMouseClicked(evt);
            }
        });

        btnSanPham.setBackground(new java.awt.Color(255, 255, 255));
        btnSanPham.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnSanPham.setForeground(new java.awt.Color(255, 255, 255));
        btnSanPham.setText("            Quản lý sản phẩm");
        btnSanPham.setMaximumSize(new java.awt.Dimension(150, 28));
        btnSanPham.setMinimumSize(new java.awt.Dimension(150, 28));
        btnSanPham.setPreferredSize(new java.awt.Dimension(150, 28));
        btnSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSanPhamMouseClicked(evt);
            }
        });

        btnNK.setBackground(new java.awt.Color(255, 255, 255));
        btnNK.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnNK.setForeground(new java.awt.Color(255, 255, 255));
        btnNK.setText("            Quản lý nhập kho");
        btnNK.setMaximumSize(new java.awt.Dimension(150, 28));
        btnNK.setMinimumSize(new java.awt.Dimension(150, 28));
        btnNK.setPreferredSize(new java.awt.Dimension(150, 28));
        btnNK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNKMouseClicked(evt);
            }
        });

        btnK.setBackground(new java.awt.Color(255, 255, 255));
        btnK.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnK.setForeground(new java.awt.Color(255, 255, 255));
        btnK.setText("            Quản lý nhập");
        btnK.setMaximumSize(new java.awt.Dimension(150, 28));
        btnK.setMinimumSize(new java.awt.Dimension(150, 28));
        btnK.setPreferredSize(new java.awt.Dimension(150, 28));
        btnK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnQLLayout = new javax.swing.GroupLayout(pnQL);
        pnQL.setLayout(pnQLLayout);
        pnQLLayout.setHorizontalGroup(
            pnQLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnQLXK, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
            .addComponent(btnSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnNK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnQLLayout.setVerticalGroup(
            pnQLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnQLLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnK, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnNK, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnQLXK, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnTT.setBackground(new java.awt.Color(255, 255, 255));
        btnTT.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnTT.setForeground(new java.awt.Color(255, 255, 255));
        btnTT.setText("Thông Tin");
        btnTT.setIconTextGap(15);
        btnTT.setMaximumSize(new java.awt.Dimension(172, 48));
        btnTT.setMinimumSize(new java.awt.Dimension(172, 48));
        btnTT.setPreferredSize(new java.awt.Dimension(172, 48));
        btnTT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTTMouseClicked(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 255, 255));
        btnExit.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Thoát");
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnExit.setFocusable(false);
        btnExit.setIconTextGap(15);
        btnExit.setMaximumSize(new java.awt.Dimension(172, 48));
        btnExit.setMinimumSize(new java.awt.Dimension(172, 48));
        btnExit.setPreferredSize(new java.awt.Dimension(172, 48));
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });
        btnExit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnExitKeyTyped(evt);
            }
        });

        btnNCC.setBackground(new java.awt.Color(255, 255, 255));
        btnNCC.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnNCC.setForeground(new java.awt.Color(255, 255, 255));
        btnNCC.setText("Quản lý nhà cung cấp");
        btnNCC.setIconTextGap(15);
        btnNCC.setMaximumSize(new java.awt.Dimension(172, 48));
        btnNCC.setMinimumSize(new java.awt.Dimension(172, 48));
        btnNCC.setPreferredSize(new java.awt.Dimension(172, 48));
        btnNCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNCCMouseClicked(evt);
            }
        });

        btnKH.setBackground(new java.awt.Color(255, 255, 255));
        btnKH.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnKH.setForeground(new java.awt.Color(255, 255, 255));
        btnKH.setText("Quản lý khách hàng");
        btnKH.setIconTextGap(15);
        btnKH.setMaximumSize(new java.awt.Dimension(172, 48));
        btnKH.setMinimumSize(new java.awt.Dimension(172, 48));
        btnKH.setPreferredSize(new java.awt.Dimension(172, 48));
        btnKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKHMouseClicked(evt);
            }
        });

        btnBC.setBackground(new java.awt.Color(255, 255, 255));
        btnBC.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnBC.setForeground(new java.awt.Color(255, 255, 255));
        btnBC.setText("Báo cáo thống kê");
        btnBC.setIconTextGap(15);
        btnBC.setMaximumSize(new java.awt.Dimension(172, 48));
        btnBC.setMinimumSize(new java.awt.Dimension(172, 48));
        btnBC.setPreferredSize(new java.awt.Dimension(172, 48));
        btnBC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBCMouseClicked(evt);
            }
        });

        pnSP.setOpaque(false);

        btnQLPT.setBackground(new java.awt.Color(255, 255, 255));
        btnQLPT.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnQLPT.setForeground(new java.awt.Color(255, 255, 255));
        btnQLPT.setText("            Quản lý phụ thu");
        btnQLPT.setMaximumSize(new java.awt.Dimension(150, 28));
        btnQLPT.setMinimumSize(new java.awt.Dimension(150, 28));
        btnQLPT.setPreferredSize(new java.awt.Dimension(150, 28));
        btnQLPT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLPTMouseClicked(evt);
            }
        });

        btnQLSP.setBackground(new java.awt.Color(255, 255, 255));
        btnQLSP.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnQLSP.setForeground(new java.awt.Color(255, 255, 255));
        btnQLSP.setText("            Quản lý sản phẩm");
        btnQLSP.setMaximumSize(new java.awt.Dimension(150, 28));
        btnQLSP.setMinimumSize(new java.awt.Dimension(150, 28));
        btnQLSP.setPreferredSize(new java.awt.Dimension(150, 28));
        btnQLSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLSPMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnSPLayout = new javax.swing.GroupLayout(pnSP);
        pnSP.setLayout(pnSPLayout);
        pnSPLayout.setHorizontalGroup(
            pnSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnQLPT, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
            .addComponent(btnQLSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnSPLayout.setVerticalGroup(
            pnSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSPLayout.createSequentialGroup()
                .addComponent(btnQLPT, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnQLSP, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnQL, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
            .addComponent(pnQL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnNCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnBC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(btnTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnQL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnQL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnBC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout pnLeftLayout = new javax.swing.GroupLayout(pnLeft);
        pnLeft.setLayout(pnLeftLayout);
        pnLeftLayout.setHorizontalGroup(
            pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnLeftLayout.setVerticalGroup(
            pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLeftLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnHome.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnHomeLayout = new javax.swing.GroupLayout(pnHome);
        pnHome.setLayout(pnHomeLayout);
        pnHomeLayout.setHorizontalGroup(
            pnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1511, Short.MAX_VALUE)
        );
        pnHomeLayout.setVerticalGroup(
            pnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQLSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLSPMouseClicked
        HideMenu();
        //        h.dispose();
        //        new frSanPham().setVisible(true);
    }//GEN-LAST:event_btnQLSPMouseClicked

    private void btnQLPTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLPTMouseClicked
//        HideMenu();
//        h.dispose();
//        try {
//            new frPhuThu().setVisible(true);
//        } catch (SQLException ex) {
//            //            Logger.getLogger(pnLeft.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_btnQLPTMouseClicked

    private void btnBCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBCMouseClicked
        boolean a = pnSP.isVisible();
        HideMenu();
        if (a==true) {
            pnSP.setVisible(false);
        } else {
            pnSP.setVisible(true);
        }
    }//GEN-LAST:event_btnBCMouseClicked

    private void btnKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKHMouseClicked
        HideMenu();
        this.dispose();
        new KhachHangView().setVisible(true);
    }//GEN-LAST:event_btnKHMouseClicked

    private void btnNCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNCCMouseClicked
        HideMenu();
        this.dispose();
        new NhaCungCapView().setVisible(true);
    }//GEN-LAST:event_btnNCCMouseClicked

    private void btnExitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnExitKeyTyped
        // TODO add your handling code here:
        //        HideMenu();
        //        h.dispose();
    }//GEN-LAST:event_btnExitKeyTyped

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        HideMenu();
        this.dispose();
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnTTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTTMouseClicked
        HideMenu();
        String tt = "";
        tt += "Phần mềm : Quản lý kho \n";
        tt += "\n ";
        tt += "version : 1.1";
        tt += "\n\n";
        tt += "_____________Bài tập lớn______________ ";
        tt += "\n\n\n";
        tt += " Trường Đại học Công Nghệ Giao Thông Vận Tải";
        tt += "\n";
        tt += " Lớp: 70DCTT21";
        tt += "\n";
        tt += " Học phần : Công nghệ phần mềm";
        tt += "\n";
        tt += "Nhóm thực hiện: Nhóm 3.";
        tt += "\n\n\nThành viên nhóm: ";
        tt += "\n         - Nhóm trưởng: Nguyễn Quang Bảo. ";
        tt += "\n         - Đội viên:    Phạm Đình Thắng. ";
        tt += "\n         - Đội viên:    Nguyễn Nghĩa Ninh. ";
        tt += "\n         - Đội viên:    Đinh Đức Mạnh. ";
        tt += "\n         - Đội viên:    Vũ Hoàng Hiếu. ";
        JOptionPane.showMessageDialog(this,tt,"Thông tin",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnTTMouseClicked

    private void btnSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSanPhamMouseClicked
        HideMenu();
        this.dispose();
        new SanPhamView().setVisible(true);
    }//GEN-LAST:event_btnSanPhamMouseClicked

    private void btnQLXKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLXKMouseClicked
        HideMenu();
        this.dispose();
        new XuatHome().setVisible(true);
    }//GEN-LAST:event_btnQLXKMouseClicked

    private void btnTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTKMouseClicked

        boolean a = pnTK.isVisible();
        HideMenu();
        if (a==true) {
            pnTK.setVisible(false);
        } else {
            pnTK.setVisible(true);
        }
    }//GEN-LAST:event_btnTKMouseClicked

    private void btnQLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLMouseClicked
        boolean a = pnQL.isVisible();
        HideMenu();
        if (a==true) {
            pnQL.setVisible(false);
        } else {
            pnQL.setVisible(true);
        }
    }//GEN-LAST:event_btnQLMouseClicked

    private void btnQLTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLTKMouseClicked
        HideMenu();
        this.dispose();
        new QuanTriView().setVisible(true);
    }//GEN-LAST:event_btnQLTKMouseClicked

    private void btnDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangXuatMouseClicked

        HideMenu();
        lblCV.setText("");
        lblTenNV.setText("");
        this.dispose();
        new PropertiesNVNow().removeRemember();
        new login().setVisible(true);
    }//GEN-LAST:event_btnDangXuatMouseClicked

    private void btnNKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNKMouseClicked
        HideMenu();
        this.dispose();
        new QLKHome().setVisible(true);
    }//GEN-LAST:event_btnNKMouseClicked

    private void btnQLNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLNVMouseClicked
        HideMenu();
        this.dispose();
        new NhanVienView().setVisible(true);
    }//GEN-LAST:event_btnQLNVMouseClicked

    private void btnKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKMouseClicked
        HideMenu();
        this.dispose();
        new KhoView().setVisible(true);
    }//GEN-LAST:event_btnKMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBC;
    private javax.swing.JLabel btnDangXuat;
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel btnK;
    private javax.swing.JLabel btnKH;
    private javax.swing.JLabel btnNCC;
    private javax.swing.JLabel btnNK;
    private javax.swing.JLabel btnQL;
    private javax.swing.JLabel btnQLNV;
    private javax.swing.JLabel btnQLPT;
    private javax.swing.JLabel btnQLSP;
    private javax.swing.JLabel btnQLTK;
    private javax.swing.JLabel btnQLXK;
    private javax.swing.JLabel btnSanPham;
    private javax.swing.JLabel btnTK;
    private javax.swing.JLabel btnTT;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblCV;
    private javax.swing.JLabel lblTenNV;
    private javax.swing.JPanel pnHome;
    private javax.swing.JPanel pnLeft;
    private javax.swing.JPanel pnQL;
    private javax.swing.JPanel pnSP;
    private javax.swing.JPanel pnTK;
    // End of variables declaration//GEN-END:variables

}
