/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QLK.Login;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.plaf.PanelUI;
import view.QuanTriView;
import view.TaiKhoanview;

/**
 *
 * @author Admins
 */
public class Home extends javax.swing.JFrame{

    /**
     * Creates new form Main
     */
    public Home() {
        initComponents();
//        setOpaque(false);
        HideMenu();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    public void PQ(){
//        PropertiesNVNow pr = new PropertiesNVNow();
//        List<String> l = pr.getRemember();
//        lblCV.setText(l.get(1));
//        lblTenNV.setText(l.get(2));
//        
//        String ma =  new PropertiesNVNow().getRemember().get(0);
//        int st = new userDao().PQ(ma);
        int st = 1;
        if(st==1){
        //Amin
        btnTK.setVisible(true);
        btnQLTK.setVisible(true);
        btnDangXuat.setVisible(true);
        
        btnQL.setVisible(true);
        btnQLKH.setVisible(true);
        btnQLNV.setVisible(true);
        btnQLP.setVisible(true);
        
        btnDV.setVisible(true);
        
        btnHD.setVisible(true);
        
        btnSP.setVisible(true);
        btnQLPT.setVisible(true);
        btnQLSP.setVisible(true);
        btnQLNK.setVisible(true);
        
        }else if(st==2){
        //quan ly
        btnTK.setVisible(true);
        btnQLTK.setVisible(false);
        btnDangXuat.setVisible(true);
        
        btnQL.setVisible(true);
        btnQLKH.setVisible(false);
        btnQLNV.setVisible(false);
        btnQLP.setVisible(false);
        
        btnDV.setVisible(true);
        
        btnHD.setVisible(false);
        
        btnSP.setVisible(true);
        btnQLPT.setVisible(true);
        btnQLSP.setVisible(false);
        btnQLNK.setVisible(true);
        
                
        }else if(st==3){
        //nhân viên
        btnTK.setVisible(true);
        btnQLTK.setVisible(false);
        btnDangXuat.setVisible(true);
        
        btnQL.setVisible(true);
        btnQLKH.setVisible(true);
        btnQLNV.setVisible(false);
        btnQLP.setVisible(true);
        
        btnDV.setVisible(true);
        
        btnHD.setVisible(false);
        
        btnSP.setVisible(false);
        btnQLPT.setVisible(true);
        btnQLSP.setVisible(false);
        btnQLNK.setVisible(true);
        
        }
    
    }
    

    public void HideMenu()
        {
            PQ();
            pnSP.setVisible(false);
            pnTK.setVisible(false);
            pnQL.setVisible(false);
            
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnLeft = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblCV2 = new javax.swing.JLabel();
        lblTenNV2 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        pnTK = new javax.swing.JPanel();
        btnDangXuat = new javax.swing.JLabel();
        btnQLTK = new javax.swing.JLabel();
        btnQL = new javax.swing.JLabel();
        btnTK = new javax.swing.JLabel();
        pnQL = new javax.swing.JPanel();
        btnQLKH = new javax.swing.JLabel();
        btnQLNV = new javax.swing.JLabel();
        btnQLP = new javax.swing.JLabel();
        btnTT = new javax.swing.JLabel();
        btnExit = new javax.swing.JLabel();
        btnDV = new javax.swing.JLabel();
        btnHD = new javax.swing.JLabel();
        btnSP = new javax.swing.JLabel();
        pnSP = new javax.swing.JPanel();
        btnQLPT = new javax.swing.JLabel();
        btnQLSP = new javax.swing.JLabel();
        btnQLNK = new javax.swing.JLabel();
        pnHome = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        pnLeft.setBackground(new java.awt.Color(0, 153, 204));

        jPanel4.setBackground(new java.awt.Color(0, 153, 204));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MIA HOTEL");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Hotels & Spa");

        lblCV2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblCV2.setForeground(new java.awt.Color(255, 255, 255));

        lblTenNV2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTenNV2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(lblCV2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTenNV2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel5))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jLabel6)))
                        .addGap(0, 53, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(14, 14, 14)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTenNV2, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(lblCV2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setOpaque(false);

        jPanel5.setOpaque(false);

        pnTK.setOpaque(false);

        btnDangXuat.setBackground(new java.awt.Color(255, 255, 255));
        btnDangXuat.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnDangXuat.setForeground(new java.awt.Color(255, 255, 255));
        btnDangXuat.setText("            Đăng xuất");
        btnDangXuat.setMaximumSize(new java.awt.Dimension(150, 28));
        btnDangXuat.setMinimumSize(new java.awt.Dimension(150, 28));
        btnDangXuat.setPreferredSize(new java.awt.Dimension(150, 28));
        btnDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDangXuatMouseClicked(evt);
            }
        });

        btnQLTK.setBackground(new java.awt.Color(255, 255, 255));
        btnQLTK.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnQLTK.setForeground(new java.awt.Color(255, 255, 255));
        btnQLTK.setText("            Quản lý tài khoản");
        btnQLTK.setMaximumSize(new java.awt.Dimension(150, 28));
        btnQLTK.setMinimumSize(new java.awt.Dimension(150, 28));
        btnQLTK.setPreferredSize(new java.awt.Dimension(150, 28));
        btnQLTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLTKMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnTKLayout = new javax.swing.GroupLayout(pnTK);
        pnTK.setLayout(pnTKLayout);
        pnTKLayout.setHorizontalGroup(
            pnTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnQLTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDangXuat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnTKLayout.setVerticalGroup(
            pnTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTKLayout.createSequentialGroup()
                .addComponent(btnQLTK, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnQL.setBackground(new java.awt.Color(255, 255, 255));
        btnQL.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnQL.setForeground(new java.awt.Color(255, 255, 255));
        btnQL.setText("Quản Lý Kho");
        btnQL.setIconTextGap(15);
        btnQL.setMaximumSize(new java.awt.Dimension(172, 48));
        btnQL.setMinimumSize(new java.awt.Dimension(172, 48));
        btnQL.setPreferredSize(new java.awt.Dimension(172, 48));
        btnQL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLMouseClicked(evt);
            }
        });

        btnTK.setBackground(new java.awt.Color(255, 255, 255));
        btnTK.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnTK.setForeground(new java.awt.Color(255, 255, 255));
        btnTK.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTK.setText("Quản trị hệ thống");
        btnTK.setIconTextGap(15);
        btnTK.setMaximumSize(new java.awt.Dimension(172, 48));
        btnTK.setMinimumSize(new java.awt.Dimension(172, 48));
        btnTK.setName(""); // NOI18N
        btnTK.setPreferredSize(new java.awt.Dimension(172, 48));
        btnTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTKMouseClicked(evt);
            }
        });

        pnQL.setOpaque(false);

        btnQLKH.setBackground(new java.awt.Color(255, 255, 255));
        btnQLKH.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnQLKH.setForeground(new java.awt.Color(255, 255, 255));
        btnQLKH.setText("            Quản lý xuất kho");
        btnQLKH.setMaximumSize(new java.awt.Dimension(150, 28));
        btnQLKH.setMinimumSize(new java.awt.Dimension(150, 28));
        btnQLKH.setPreferredSize(new java.awt.Dimension(150, 28));
        btnQLKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLKHMouseClicked(evt);
            }
        });

        btnQLNV.setBackground(new java.awt.Color(255, 255, 255));
        btnQLNV.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnQLNV.setForeground(new java.awt.Color(255, 255, 255));
        btnQLNV.setText("            Quản lý nhập kho");
        btnQLNV.setMaximumSize(new java.awt.Dimension(150, 28));
        btnQLNV.setMinimumSize(new java.awt.Dimension(150, 28));
        btnQLNV.setPreferredSize(new java.awt.Dimension(150, 28));
        btnQLNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLNVMouseClicked(evt);
            }
        });

        btnQLP.setBackground(new java.awt.Color(255, 255, 255));
        btnQLP.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnQLP.setForeground(new java.awt.Color(255, 255, 255));
        btnQLP.setText("            Quản lý sản phẩm");
        btnQLP.setMaximumSize(new java.awt.Dimension(150, 28));
        btnQLP.setMinimumSize(new java.awt.Dimension(150, 28));
        btnQLP.setPreferredSize(new java.awt.Dimension(150, 28));
        btnQLP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLPMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnQLLayout = new javax.swing.GroupLayout(pnQL);
        pnQL.setLayout(pnQLLayout);
        pnQLLayout.setHorizontalGroup(
            pnQLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnQLKH, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
            .addComponent(btnQLP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnQLNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnQLLayout.setVerticalGroup(
            pnQLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnQLLayout.createSequentialGroup()
                .addComponent(btnQLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnQLKH, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnQLP, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnTT.setBackground(new java.awt.Color(255, 255, 255));
        btnTT.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnTT.setForeground(new java.awt.Color(255, 255, 255));
        btnTT.setText("Thông Tin");
        btnTT.setIconTextGap(15);
        btnTT.setMaximumSize(new java.awt.Dimension(172, 48));
        btnTT.setMinimumSize(new java.awt.Dimension(172, 48));
        btnTT.setPreferredSize(new java.awt.Dimension(172, 48));
        btnTT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTTMouseClicked(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 255, 255));
        btnExit.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Thoát");
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnExit.setFocusable(false);
        btnExit.setIconTextGap(15);
        btnExit.setMaximumSize(new java.awt.Dimension(172, 48));
        btnExit.setMinimumSize(new java.awt.Dimension(172, 48));
        btnExit.setPreferredSize(new java.awt.Dimension(172, 48));
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });
        btnExit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnExitKeyTyped(evt);
            }
        });

        btnDV.setBackground(new java.awt.Color(255, 255, 255));
        btnDV.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnDV.setForeground(new java.awt.Color(255, 255, 255));
        btnDV.setText("Quản lý nhà cung cấp");
        btnDV.setIconTextGap(15);
        btnDV.setMaximumSize(new java.awt.Dimension(172, 48));
        btnDV.setMinimumSize(new java.awt.Dimension(172, 48));
        btnDV.setPreferredSize(new java.awt.Dimension(172, 48));
        btnDV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDVMouseClicked(evt);
            }
        });

        btnHD.setBackground(new java.awt.Color(255, 255, 255));
        btnHD.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnHD.setForeground(new java.awt.Color(255, 255, 255));
        btnHD.setText("Quản lý khách hàng");
        btnHD.setIconTextGap(15);
        btnHD.setMaximumSize(new java.awt.Dimension(172, 48));
        btnHD.setMinimumSize(new java.awt.Dimension(172, 48));
        btnHD.setPreferredSize(new java.awt.Dimension(172, 48));
        btnHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHDMouseClicked(evt);
            }
        });

        btnSP.setBackground(new java.awt.Color(255, 255, 255));
        btnSP.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnSP.setForeground(new java.awt.Color(255, 255, 255));
        btnSP.setText("Báo cáo thống kê");
        btnSP.setIconTextGap(15);
        btnSP.setMaximumSize(new java.awt.Dimension(172, 48));
        btnSP.setMinimumSize(new java.awt.Dimension(172, 48));
        btnSP.setPreferredSize(new java.awt.Dimension(172, 48));
        btnSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSPMouseClicked(evt);
            }
        });

        pnSP.setOpaque(false);

        btnQLPT.setBackground(new java.awt.Color(255, 255, 255));
        btnQLPT.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnQLPT.setForeground(new java.awt.Color(255, 255, 255));
        btnQLPT.setText("            Quản lý phụ thu");
        btnQLPT.setMaximumSize(new java.awt.Dimension(150, 28));
        btnQLPT.setMinimumSize(new java.awt.Dimension(150, 28));
        btnQLPT.setPreferredSize(new java.awt.Dimension(150, 28));
        btnQLPT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLPTMouseClicked(evt);
            }
        });

        btnQLSP.setBackground(new java.awt.Color(255, 255, 255));
        btnQLSP.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnQLSP.setForeground(new java.awt.Color(255, 255, 255));
        btnQLSP.setText("            Quản lý sản phẩm");
        btnQLSP.setMaximumSize(new java.awt.Dimension(150, 28));
        btnQLSP.setMinimumSize(new java.awt.Dimension(150, 28));
        btnQLSP.setPreferredSize(new java.awt.Dimension(150, 28));
        btnQLSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLSPMouseClicked(evt);
            }
        });

        btnQLNK.setBackground(new java.awt.Color(255, 255, 255));
        btnQLNK.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnQLNK.setForeground(new java.awt.Color(255, 255, 255));
        btnQLNK.setText("            Quản lý nhập kho");
        btnQLNK.setMaximumSize(new java.awt.Dimension(150, 28));
        btnQLNK.setMinimumSize(new java.awt.Dimension(150, 28));
        btnQLNK.setPreferredSize(new java.awt.Dimension(150, 28));
        btnQLNK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLNKMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnSPLayout = new javax.swing.GroupLayout(pnSP);
        pnSP.setLayout(pnSPLayout);
        pnSPLayout.setHorizontalGroup(
            pnSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnQLPT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnQLSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnQLNK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnSPLayout.setVerticalGroup(
            pnSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSPLayout.createSequentialGroup()
                .addComponent(btnQLPT, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnQLSP, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnQLNK, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnQL, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
            .addComponent(pnQL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(btnTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnQL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnQL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout pnLeftLayout = new javax.swing.GroupLayout(pnLeft);
        pnLeft.setLayout(pnLeftLayout);
        pnLeftLayout.setHorizontalGroup(
            pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnLeftLayout.setVerticalGroup(
            pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLeftLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        pnHome.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnHomeLayout = new javax.swing.GroupLayout(pnHome);
        pnHome.setLayout(pnHomeLayout);
        pnHomeLayout.setHorizontalGroup(
            pnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 779, Short.MAX_VALUE)
        );
        pnHomeLayout.setVerticalGroup(
            pnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQLNKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLNKMouseClicked
        //        HideMenu();
        //        h.dispose();
        //        new QLNK().setVisible(true);
    }//GEN-LAST:event_btnQLNKMouseClicked

    private void btnQLSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLSPMouseClicked
        HideMenu();
        //        h.dispose();
        //        new frSanPham().setVisible(true);
    }//GEN-LAST:event_btnQLSPMouseClicked

    private void btnQLPTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLPTMouseClicked
//        HideMenu();
//        h.dispose();
//        try {
//            new frPhuThu().setVisible(true);
//        } catch (SQLException ex) {
//            //            Logger.getLogger(pnLeft.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_btnQLPTMouseClicked

    private void btnSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSPMouseClicked
        boolean a = pnSP.isVisible();
        HideMenu();
        if (a==true) {
            pnSP.setVisible(false);
        } else {
            pnSP.setVisible(true);
        }
    }//GEN-LAST:event_btnSPMouseClicked

    private void btnHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHDMouseClicked
        //        HideMenu();
        //        h.dispose();
        //        try {
            //            new ChiTietHoaDon().setVisible(true);
            //        } catch (SQLException ex) {
            //            Logger.getLogger(pnLeft.class.getName()).log(Level.SEVERE, null, ex);
            //        }
    }//GEN-LAST:event_btnHDMouseClicked

    private void btnDVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDVMouseClicked
        //        HideMenu();
        //        h.dispose();
        //        new TrangChuDichVu().setVisible(true);
    }//GEN-LAST:event_btnDVMouseClicked

    private void btnExitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnExitKeyTyped
        // TODO add your handling code here:
        //        HideMenu();
        //        h.dispose();
    }//GEN-LAST:event_btnExitKeyTyped

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        //        HideMenu();
        //        h.dispose();
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnTTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTTMouseClicked
        HideMenu();
        String tt = "";
        tt += "Phần mềm : Quản lý Khách sạn MIA \n";
        tt += "\n ";
        tt += "version : 1.1";
        tt += "\n\n";
        tt += "_____________Bài tập lớn______________ ";
        tt += "\n\n\n";
        tt += " Trường Đại học Công Nghệ Giao Thông Vận Tải";
        tt += "\n";
        tt += " Lớp: 70DCTT21";
        tt += "\n";
        tt += " Học phần : Lập trình java nâng cao";
        tt += "\n";
        tt += "Nhóm thực hiện: Nhóm 3.";
        tt += "\n\n\nThành viên nhóm: ";
        tt += "\n         - Nhóm trưởng: Nguyễn Quang Bảo. ";
        tt += "\n         - Đội viên:    Phạm Đình Thắng. ";
        tt += "\n         - Đội viên:    Nguyễn Nghĩa Ninh. ";
        tt += "\n         - Đội viên:    Đinh Đức Mạnh. ";
        JOptionPane.showMessageDialog(this,tt,"Thông tin",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnTTMouseClicked

    private void btnQLPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLPMouseClicked
        //        HideMenu();
        //        h.dispose();
        //        new ThongTinPhong().setVisible(true);
    }//GEN-LAST:event_btnQLPMouseClicked

    private void btnQLNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLNVMouseClicked
        //        HideMenu();
        //        h.dispose();
        //        new Staffview().setVisible(true);
    }//GEN-LAST:event_btnQLNVMouseClicked

    private void btnQLKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLKHMouseClicked
        //        HideMenu();
        //        h.dispose();
        //        new Customview().setVisible(true);
    }//GEN-LAST:event_btnQLKHMouseClicked

    private void btnTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTKMouseClicked

        boolean a = pnTK.isVisible();
        HideMenu();
        if (a==true) {
            pnTK.setVisible(false);
        } else {
            pnTK.setVisible(true);
        }
    }//GEN-LAST:event_btnTKMouseClicked

    private void btnQLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLMouseClicked
        boolean a = pnQL.isVisible();
        HideMenu();
        if (a==true) {
            pnQL.setVisible(false);
        } else {
            pnQL.setVisible(true);
        }
    }//GEN-LAST:event_btnQLMouseClicked

    private void btnQLTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLTKMouseClicked
                HideMenu();
                this.dispose();
                new QuanTriView().setVisible(true);
    }//GEN-LAST:event_btnQLTKMouseClicked

    private void btnDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangXuatMouseClicked

        //        HideMenu();
        //        lblCV.setText("");
        //        lblTenNV.setText("");
        //        h.dispose();
        //        new login().setVisible(true);
    }//GEN-LAST:event_btnDangXuatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnDV;
    private javax.swing.JLabel btnDangXuat;
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel btnHD;
    private javax.swing.JLabel btnQL;
    private javax.swing.JLabel btnQLKH;
    private javax.swing.JLabel btnQLNK;
    private javax.swing.JLabel btnQLNV;
    private javax.swing.JLabel btnQLP;
    private javax.swing.JLabel btnQLPT;
    private javax.swing.JLabel btnQLSP;
    private javax.swing.JLabel btnQLTK;
    private javax.swing.JLabel btnSP;
    private javax.swing.JLabel btnTK;
    private javax.swing.JLabel btnTT;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblCV2;
    private javax.swing.JLabel lblTenNV2;
    private javax.swing.JPanel pnHome;
    private javax.swing.JPanel pnLeft;
    private javax.swing.JPanel pnQL;
    private javax.swing.JPanel pnSP;
    private javax.swing.JPanel pnTK;
    // End of variables declaration//GEN-END:variables

}
